### ISSUE TITLE
probably won't build on raspberr pi V1 or zero

### ISSUE THREAD

**Issue by shaunmulligan** [resin-io-projects/resin-rust-hello-world#2]
On our docker hub images set we dont have a `-debian` for RPI v1 architecture, instead it is `-raspbian` which means this will fail. 
`FROM resin/%%RESIN_MACHINE_NAME%%-debian`
This is an issue with our `Dockerfile.templates` and naming standard on dockerhub.

**Comment by pcarranzav** [comment]
Another reason for this is that the kernel during build time is armv7, so the arm-unknown-linux-gnueabi target should be manually installed and used in the `RUN cargo build` step.
(This will probably require a separate branch for armv6)

**Comment by shaunmulligan** [comment]
we now have [resin/raspberry-pi-debian]( https://hub.docker.com/r/resin/raspberry-pi-debian/ ) images so this issue should not be a problem any more

**Comment by zrzka** [comment]
Based [on this comment](https://github.com/resin-io-projects/resin-rust-hello-world/issues/2#issuecomment-385920076), going to close this issue. If it's still valid, feel free to reopen.

**Comment by rahul-thakoor** [comment]
Hello, I am trying to run the `resin-rust-hello-world` example on **raspberry pi zero w** and **raspberry pi v1**. I am expecting to see `hello-world` in the logs, however, the service starts but there is no such output.
I tried to ssh into the service and run the `hello` program manually but got this error:

```
root@a708022:/app# ./hello
Illegal instruction (core dumped)
```
How can I fix this issue? Is it because of the image?

Thanks!

**Comment by zrzka** [comment]
@rahul-thakoor thanks for the report. Couple of questions.

**What's the content of your `local-push.env` file? Does it contain correct image?**

Here's one for Raspberry Pi 3B+:

```bash
$ cat local-push.env
export RESIN_MACHINE_NAME=raspberrypi3
```

It should be `raspberry-pi` for Raspberry Pi v1 & ZERO. Visit [Resin.io base images](https://docs.resin.io/reference/base-images/base-images/) for more details.

But I assume you have correct value set, because the system is up & running, only the application doesn't work.

**Dockerfile.template**

Because of the _Illegal instruction_, I assume it's ARMv6 (Pi V1 & Zero) vs ARMv7 (Pi 3B+) issue.

This project was done for the Raspberry Pi 3B+. And because of other issue (see [comments](https://github.com/resin-io-projects/resin-rust-hello-world/blob/master/Dockerfile.template#L26-L30) in the `Dockerfile.template` file), I had to replace `uname` with simple `echo armv7l`. Check [this line](https://github.com/resin-io-projects/resin-rust-hello-world/blob/master/Dockerfile.template#L31). It should help / fix your issue if you remove / comment this line. Does it help?

**Comment by rahul-thakoor** [comment]
@zrzka thanks for the prompt response!

Commenting out the [line ](https://github.com/resin-io-projects/resin-rust-hello-world/blob/master/Dockerfile.template#L31) breaks the build.
I instead changed `armv7l` -> `armv6l` and it builds. However, I am not sure if `armv6l` is a proper architecture identifier?
![image](https://user-images.githubusercontent.com/13220877/44223675-5270ea00-a199-11e8-9957-51c12a260bab.png)

**Comment by zrzka** [comment]
Yes, it is. I'm going to close this in favor of #10.
